<?php

namespace App\Console\Commands;

use App\Models\Brand;
use App\Models\Category;
use App\Models\HeroSlide;
use App\Models\MenuItem;
use App\Models\Page;
use App\Models\Product;
use App\Models\SchemaSetting;
use App\Models\Store;
use App\Models\UspBlock;
use Illuminate\Console\Command;
use Illuminate\Support\Facades\File;
use Illuminate\Support\Str;
use Spatie\Image\Image;
use Spatie\MediaLibrary\MediaCollections\Models\Media;

/**
 * Exports the current database content (categories, brands, stores, products,
 * hero slides, USP blocks, menu items, pages and schema settings) plus their
 * uploaded photos into database/seeders/ProductionSeeder.php and
 * database/seeders/media/, so the exact same content can be recreated on a
 * fresh install (e.g. the live/production site) by running:
 *
 *   php artisan db:seed --class=ProductionSeeder
 *
 * Re-run this command any time to refresh the export with the latest content.
 */
class ExportContentSeeder extends Command
{
    protected $signature = 'app:export-content-seeder';

    protected $description = 'Export the current database content and media into a seeder for deploying the same data elsewhere';

    private string $mediaPath;

    public function handle(): int
    {
        $this->mediaPath = database_path('seeders/media');
        File::deleteDirectory($this->mediaPath);
        File::ensureDirectoryExists($this->mediaPath);

        $php = "<?php\n\nnamespace Database\\Seeders;\n\n";
        $php .= "use App\\Models\\Brand;\n";
        $php .= "use App\\Models\\Category;\n";
        $php .= "use App\\Models\\HeroSlide;\n";
        $php .= "use App\\Models\\MenuItem;\n";
        $php .= "use App\\Models\\Page;\n";
        $php .= "use App\\Models\\Product;\n";
        $php .= "use App\\Models\\SchemaSetting;\n";
        $php .= "use App\\Models\\Store;\n";
        $php .= "use App\\Models\\UspBlock;\n";
        $php .= "use Illuminate\\Database\\Seeder;\n\n";
        $php .= "/**\n * Generated by `php artisan app:export-content-seeder`. Do not edit by hand,\n * re-run the command instead so this file stays in sync with the database.\n */\n";
        $php .= "class ProductionSeeder extends Seeder\n{\n";
        $php .= "    public function run(): void\n    {\n";

        $php .= $this->exportCategories();
        $php .= $this->exportBrands();
        $php .= $this->exportStores();
        $php .= $this->exportProducts();
        $php .= $this->exportHeroSlides();
        $php .= $this->exportUspBlocks();
        $php .= $this->exportPages();
        $php .= $this->exportMenuItems();
        $php .= $this->exportSchemaSettings();

        $php .= "    }\n";
        $php .= "}\n";

        File::put(database_path('seeders/ProductionSeeder.php'), $php);

        $this->info('Seeder written to database/seeders/ProductionSeeder.php');
        $this->info('Media files copied to database/seeders/media/');
        $this->info('Run it with: php artisan db:seed --class=ProductionSeeder');

        return self::SUCCESS;
    }

    private function exportCategories(): string
    {
        $out = "        // Categories\n";
        $out .= "        \$categories = [];\n";

        foreach (Category::orderBy('sort_order')->get() as $category) {
            $data = $category->only([
                'name', 'slug', 'icon', 'description',
                'why_kicker', 'why_title', 'why_text', 'gift_kicker', 'gift_title', 'gift_text',
                'show_featured_products', 'allow_exchange',
                'meta_title', 'meta_description', 'is_active', 'sort_order',
            ]);

            $out .= "        \$categories['{$category->slug}'] = Category::create(".$this->exportArray($data).");\n";
            $out .= $this->exportMediaFor($category, 'photo', "\$categories['{$category->slug}']");
            $out .= $this->exportMediaFor($category, 'feature_photo', "\$categories['{$category->slug}']");
            $out .= $this->exportMediaFor($category, 'gift_photo', "\$categories['{$category->slug}']");
        }

        if ($parents = Category::whereNotNull('parent_id')->get()) {
            foreach ($parents as $child) {
                $parentSlug = Category::find($child->parent_id)?->slug;
                if ($parentSlug) {
                    $out .= "        \$categories['{$child->slug}']->update(['parent_id' => \$categories['{$parentSlug}']->id]);\n";
                }
            }
        }

        return $out."\n";
    }

    private function exportBrands(): string
    {
        $out = "        // Brands\n";
        $out .= "        \$brands = [];\n";

        foreach (Brand::orderBy('sort_order')->get() as $brand) {
            $data = $brand->only([
                'name', 'slug', 'description', 'website_url',
                'meta_title', 'meta_description', 'is_active', 'sort_order',
            ]);

            $out .= "        \$brands['{$brand->slug}'] = Brand::create(".$this->exportArray($data).");\n";
            $out .= $this->exportMediaFor($brand, 'logo', "\$brands['{$brand->slug}']");
        }

        return $out."\n";
    }

    private function exportStores(): string
    {
        $out = "        // Stores\n";
        $out .= "        \$stores = [];\n";

        foreach (Store::orderBy('sort_order')->get() as $store) {
            $data = $store->only([
                'name', 'slug', 'address_line', 'postal_code', 'city',
                'phone', 'email', 'shopping_center', 'description',
                'latitude', 'longitude', 'google_maps_url',
                'meta_title', 'meta_description', 'is_active', 'sort_order',
            ]);

            $out .= "        \$stores['{$store->slug}'] = Store::create(".$this->exportArray($data).");\n";
            $out .= $this->exportMediaFor($store, 'photo', "\$stores['{$store->slug}']");
            $out .= $this->exportMediaFor($store, 'area_photo', "\$stores['{$store->slug}']");

            foreach ($store->openingHours as $hour) {
                $hourData = $hour->only(['day_of_week', 'opens_at', 'closes_at', 'is_closed']);
                $out .= "        \$stores['{$store->slug}']->openingHours()->create(".$this->exportArray($hourData).");\n";
            }
        }

        return $out."\n";
    }

    private function exportProducts(): string
    {
        $out = "        // Products\n";
        $out .= "        \$products = [];\n";

        foreach (Product::orderBy('sort_order')->get() as $product) {
            $data = $product->only([
                'name', 'slug', 'short_description', 'description',
                'price', 'price_label', 'is_featured', 'meta_title', 'meta_description',
                'is_active', 'sort_order',
            ]);
            $brandSlug = $product->brand?->slug;

            $out .= "        \$products['{$product->slug}'] = Product::create(".$this->exportArray($data).' + [\'brand_id\' => $brands[\''.$brandSlug."']->id]);\n";
            $out .= $this->exportMediaFor($product, 'gallery', "\$products['{$product->slug}']");

            $categorySlugs = $product->categories->pluck('slug')->all();
            if ($categorySlugs) {
                $keys = collect($categorySlugs)->map(fn ($slug) => "\$categories['{$slug}']->id")->implode(', ');
                $out .= "        \$products['{$product->slug}']->categories()->attach([{$keys}]);\n";
            }
        }

        return $out."\n";
    }

    private function exportHeroSlides(): string
    {
        $out = "        // Hero slides\n";

        foreach (HeroSlide::orderBy('sort_order')->get() as $slide) {
            $data = $slide->only(['kicker', 'title', 'subtitle', 'button_label', 'button_url', 'sort_order', 'is_active']);
            $var = '$slide'.$slide->id;
            $out .= "        {$var} = HeroSlide::create(".$this->exportArray($data).");\n";
            $out .= $this->exportMediaFor($slide, 'image', $var);
        }

        return $out."\n";
    }

    private function exportUspBlocks(): string
    {
        $out = "        // USP blocks\n";

        foreach (UspBlock::orderBy('sort_order')->get() as $block) {
            $data = $block->only(['icon', 'title', 'text', 'sort_order', 'is_active']);
            $out .= "        UspBlock::create(".$this->exportArray($data).");\n";
        }

        return $out."\n";
    }

    private function exportPages(): string
    {
        $out = "        // Pages\n";
        $out .= "        \$pages = [];\n";

        foreach (Page::orderBy('id')->get() as $page) {
            $data = $page->only(['title', 'slug', 'body', 'template', 'meta_title', 'meta_description', 'is_published']);
            $data['published_at'] = $page->published_at?->toDateTimeString();

            $out .= "        \$pages['{$page->slug}'] = Page::create(".$this->exportArray($data).");\n";
        }

        return $out."\n";
    }

    private function exportMenuItems(): string
    {
        $out = "        // Menu items\n";

        $linkableMap = [
            Category::class => 'categories',
            Store::class => 'stores',
            Page::class => 'pages',
        ];

        foreach (MenuItem::orderBy('location')->orderBy('sort_order')->get() as $item) {
            $data = $item->only(['location', 'label', 'url', 'target', 'sort_order', 'is_active']);

            if ($item->linkable_type && isset($linkableMap[$item->linkable_type])) {
                $slug = $item->linkable?->slug;
                $varName = $linkableMap[$item->linkable_type];
                $out .= "        MenuItem::create(".$this->exportArray($data)." + [\n";
                $out .= "            'linkable_type' => {$this->exportClassConst($item->linkable_type)},\n";
                $out .= "            'linkable_id' => \${$varName}['{$slug}']->id,\n";
                $out .= "        ]);\n";
            } else {
                $out .= "        MenuItem::create(".$this->exportArray($data).");\n";
            }
        }

        return $out."\n";
    }

    private function exportSchemaSettings(): string
    {
        $out = "        // Schema / site settings\n";

        foreach (SchemaSetting::orderBy('key')->get() as $setting) {
            $out .= "        SchemaSetting::set('{$setting->key}', ".$this->exportValue($setting->value).");\n";
        }

        return $out."\n";
    }

    /**
     * Copies every media file for the given model/collection into
     * database/seeders/media/ and returns the PHP lines that re-attach it.
     */
    private function exportMediaFor(mixed $model, string $collection, string $varExpression): string
    {
        $items = $model->getMedia($collection);

        if ($items->isEmpty()) {
            return '';
        }

        $out = '';

        foreach ($items as $media) {
            /** @var Media $media */
            $sourcePath = $media->getPath();

            if (! is_file($sourcePath)) {
                continue;
            }

            $modelFolder = Str::snake(class_basename($model));
            $relativeDir = "{$modelFolder}/{$model->id}/{$collection}";
            $destDir = "{$this->mediaPath}/{$relativeDir}";
            File::ensureDirectoryExists($destDir);

            $filename = $media->file_name;
            $destPath = "{$destDir}/{$filename}";
            File::copy($sourcePath, $destPath);
            $this->shrinkIfNeeded($destPath);

            $fixturePath = "database_path('seeders/media/{$relativeDir}/{$filename}')";
            $out .= "        {$varExpression}->addMedia({$fixturePath})->preservingOriginal()->toMediaCollection('{$collection}');\n";
        }

        return $out;
    }

    /**
     * Downscales and compresses a fixture image if it's larger than needed.
     * The largest conversion anywhere on the site is 1600px wide, so nothing
     * bigger than that is useful, and it keeps memory use low when the
     * conversions are (re)generated on a low-memory hosting plan.
     */
    private function shrinkIfNeeded(string $path): void
    {
        $maxDimension = 2000;

        $image = Image::load($path);

        if ($image->getWidth() <= $maxDimension && $image->getHeight() <= $maxDimension) {
            return;
        }

        if ($image->getWidth() >= $image->getHeight()) {
            $image->width($maxDimension);
        } else {
            $image->height($maxDimension);
        }

        $image->quality(80)->save($path);
    }

    private function exportArray(array $data): string
    {
        $lines = ['['];

        foreach ($data as $key => $value) {
            $lines[] = "            '{$key}' => ".$this->exportValue($value).',';
        }

        $lines[] = '        ]';

        return implode("\n", $lines);
    }

    private function exportValue(mixed $value): string
    {
        if (is_null($value)) {
            return 'null';
        }

        if (is_bool($value)) {
            return $value ? 'true' : 'false';
        }

        if (is_array($value)) {
            $lines = ['['];
            $isList = array_is_list($value);
            foreach ($value as $k => $v) {
                $lines[] = $isList
                    ? '                '.$this->exportValue($v).','
                    : '                '.var_export((string) $k, true).' => '.$this->exportValue($v).',';
            }
            $lines[] = '            ]';

            return implode("\n", $lines);
        }

        return var_export($value, true);
    }

    private function exportClassConst(string $class): string
    {
        return class_basename($class).'::class';
    }
}
