<?php

namespace Database\Seeders;

use App\Models\Brand;
use App\Models\Category;
use App\Models\HeroSlide;
use App\Models\MenuItem;
use App\Models\Page;
use App\Models\Product;
use App\Models\SchemaSetting;
use App\Models\Store;
use App\Models\UspBlock;
use Illuminate\Database\Seeder;

/**
 * Generated by `php artisan app:export-content-seeder`. Do not edit by hand,
 * re-run the command instead so this file stays in sync with the database.
 */
class ProductionSeeder extends Seeder
{
    public function run(): void
    {
        // Categories
        $categories = [];
        $categories['tassen'] = Category::create([
            'name' => 'Tassen',
            'slug' => 'tassen',
            'icon' => 'bi-bag-fill',
            'description' => '<p>Van stoere schoudertassen tot elegante clutches. Ons assortiment tassen wisselt continu, kom langs in de winkel om te zien, voelen en passen.</p>',
            'why_kicker' => 'Waarom Nice2Have',
            'why_title' => 'Voor elke gelegenheid de juiste tas',
            'why_text' => 'Bij Nice2Have vind je een ruime keuze tassen van merken als Josh, Qoss, Micmac Bags, Beagles, Charm London en Hide & Stitches. Van een ruime shopper voor dagelijks gebruik tot een chique clutch voor een avondje uit. Ons aanbod wisselt continu, dus er is altijd wel iets nieuws te ontdekken.',
            'gift_kicker' => 'Cadeautip',
            'gift_title' => 'Twijfel je welke tas het wordt?',
            'gift_text' => 'Een tas is altijd een fijn cadeau, maar de keuze is groot. Onze medewerkers denken graag met je mee over kleur, maat en merk, of kies voor een cadeaubon zodat ze zelf hun favoriet kunnen uitzoeken.',
            'show_featured_products' => true,
            'allow_exchange' => true,
            'meta_title' => null,
            'meta_description' => null,
            'is_active' => true,
            'sort_order' => 1,
        ]);
        $categories['tassen']->addMedia(database_path('seeders/media/category/1/photo/01KYAVY8BSN3F1TBE80KABGTYB.JPG'))->preservingOriginal()->toMediaCollection('photo');
        $categories['tassen']->addMedia(database_path('seeders/media/category/1/feature_photo/01KYAVYB5YZMYXYRWZK6DX1NN6.JPG'))->preservingOriginal()->toMediaCollection('feature_photo');
        $categories['tassen']->addMedia(database_path('seeders/media/category/1/gift_photo/01KYAVYDECQVW1X6Y611AM3VK3.JPG'))->preservingOriginal()->toMediaCollection('gift_photo');
        $categories['sieraden'] = Category::create([
            'name' => 'Sieraden',
            'slug' => 'sieraden',
            'icon' => 'bi-gem',
            'description' => '<p>Ringen, armbanden, kettingen en oorbellen om te combineren en te stapelen. Ons assortiment sieraden wisselt continu, kom langs in de winkel om te zien, voelen en passen.</p>',
            'why_kicker' => 'Waarom Nice2Have',
            'why_title' => 'Bouw je eigen sieradenlook',
            'why_text' => 'Bij Nice2Have vind je merken voor elke stijl, van modulaire armbanden en kettingen van ixxxi en Melano tot tijdloze sieraden van Karma, Biba, Uno de 50 en Zinzi. Combineer, stapel en wissel net zo vaak als je zelf wilt.',
            'gift_kicker' => 'Cadeautip',
            'gift_title' => 'Een sieraad is altijd een goed idee',
            'gift_text' => 'Twijfel je nog wat je iemand cadeau doet? Een sieraad van ixxxi, Melano of Karma is persoonlijk en tijdloos. Kom langs voor advies in de winkel, of kies voor een cadeaubon zodat ze zelf kunnen kiezen.',
            'show_featured_products' => true,
            'allow_exchange' => true,
            'meta_title' => null,
            'meta_description' => null,
            'is_active' => true,
            'sort_order' => 2,
        ]);
        $categories['sieraden']->addMedia(database_path('seeders/media/category/2/photo/01KYAVW4M2WY5S77HWCQV05BY8.JPG'))->preservingOriginal()->toMediaCollection('photo');
        $categories['sieraden']->addMedia(database_path('seeders/media/category/2/feature_photo/01KYRB8EE59MR1TV5J54XA7FDX.JPG'))->preservingOriginal()->toMediaCollection('feature_photo');
        $categories['sieraden']->addMedia(database_path('seeders/media/category/2/gift_photo/01KYRB8HGJQHV1YZ71PG2XAF8N.JPG'))->preservingOriginal()->toMediaCollection('gift_photo');
        $categories['horloges'] = Category::create([
            'name' => 'Horloges',
            'slug' => 'horloges',
            'icon' => 'bi-smartwatch',
            'description' => '<p>Van tijdloos en minimalistisch tot een echte eyecatcher. Ons assortiment horloges wisselt continu, kom langs in de winkel om te zien, voelen en passen.</p>',
            'why_kicker' => 'Waarom Nice2Have',
            'why_title' => 'Een horloge dat bij je past',
            'why_text' => 'Bij Nice2Have vind je horloges van Cluse, Oozoo, Olympic en Zinzi. Van minimalistisch en tijdloos tot een stoere eyecatcher, er is altijd een horloge dat aansluit bij jouw stijl.',
            'gift_kicker' => 'Cadeautip',
            'gift_title' => 'Een horloge is een cadeau voor altijd',
            'gift_text' => 'Twijfel je welk model of merk het beste past? Onze medewerkers helpen je graag kiezen, of kies voor een cadeaubon zodat ze zelf hun favoriet kunnen uitzoeken.',
            'show_featured_products' => true,
            'allow_exchange' => true,
            'meta_title' => null,
            'meta_description' => null,
            'is_active' => true,
            'sort_order' => 3,
        ]);
        $categories['horloges']->addMedia(database_path('seeders/media/category/3/photo/01KYAVVB5XCWQRQ5WR1RG36NDR.JPG'))->preservingOriginal()->toMediaCollection('photo');
        $categories['horloges']->addMedia(database_path('seeders/media/category/3/feature_photo/01KYRBAZNMHXZSRH3B9M19ZBPX.JPG'))->preservingOriginal()->toMediaCollection('feature_photo');
        $categories['horloges']->addMedia(database_path('seeders/media/category/3/gift_photo/01KYRBB1TQN8QH848N2QCQS2DA.JPG'))->preservingOriginal()->toMediaCollection('gift_photo');
        $categories['riemen-sjaals'] = Category::create([
            'name' => 'Riemen & Sjaals',
            'slug' => 'riemen-sjaals',
            'icon' => 'bi-tags-fill',
            'description' => '<p>De perfecte finishing touch voor iedere outfit. Ons assortiment riemen en sjaals wisselt continu, kom langs in de winkel om te zien, voelen en passen.</p>',
            'why_kicker' => 'Waarom Nice2Have',
            'why_title' => 'Het detail dat je outfit compleet maakt',
            'why_text' => 'Een riem of sjaal maakt een outfit vaak net af. Bij Nice2Have vind je een wisselend aanbod in verschillende kleuren, materialen en stijlen, van subtiel tot een echte statementsjaal.',
            'gift_kicker' => 'Cadeautip',
            'gift_title' => 'Klein cadeau, groot effect',
            'gift_text' => 'Op zoek naar een leuk cadeau zonder hoofdbrekens? Een sjaal of riem is altijd een schot in de roos. Kom langs in de winkel voor advies, of kies voor een cadeaubon.',
            'show_featured_products' => false,
            'allow_exchange' => true,
            'meta_title' => null,
            'meta_description' => null,
            'is_active' => true,
            'sort_order' => 4,
        ]);
        $categories['riemen-sjaals']->addMedia(database_path('seeders/media/category/4/photo/01KYAVWZY1KSMPBDMQW2VHGTNA.JPG'))->preservingOriginal()->toMediaCollection('photo');
        $categories['riemen-sjaals']->addMedia(database_path('seeders/media/category/4/feature_photo/01KYRBETV53BPR588B54MZ03F4.JPG'))->preservingOriginal()->toMediaCollection('feature_photo');
        $categories['riemen-sjaals']->addMedia(database_path('seeders/media/category/4/gift_photo/01KYRBEYEE156H7V2ZASKDVSRD.JPG'))->preservingOriginal()->toMediaCollection('gift_photo');
        $categories['tapparfum'] = Category::create([
            'name' => 'Tapparfum',
            'slug' => 'tapparfum',
            'icon' => null,
            'description' => '<p>Kies uit maar liefst 160 verschillende geuren bij onze Tapparfum-bar. Kom langs in de winkel om je favoriet te ontdekken.</p>',
            'why_kicker' => 'Waarom Nice2Have',
            'why_title' => 'Jouw geur, getapt naar wens',
            'why_text' => 'Bij onze Tapparfum-bar kies je uit maar liefst 160 verschillende geuren. Van fris en fruitig tot warm en kruidig, er is altijd een geur die helemaal bij jou past. Kom langs, ruik en ontdek je favoriet.',
            'gift_kicker' => 'Cadeautip',
            'gift_title' => 'Een geur cadeau doen',
            'gift_text' => 'Twijfel je welke geur iemand mooi zou vinden? Kom samen langs in de winkel en ontdek de mogelijkheden, of kies voor een cadeaubon zodat ze zelf hun favoriete geur kunnen tappen.',
            'show_featured_products' => false,
            'allow_exchange' => false,
            'meta_title' => 'Tapparfum bij ons verkrijgbaar',
            'meta_description' => null,
            'is_active' => true,
            'sort_order' => 5,
        ]);
        $categories['tapparfum']->addMedia(database_path('seeders/media/category/5/photo/01KYRBK02A61WJ0VXY6YCQHNR3.JPG'))->preservingOriginal()->toMediaCollection('photo');
        $categories['tapparfum']->addMedia(database_path('seeders/media/category/5/feature_photo/01KYRBK3HHWBYA9G5TJQ0TRBFF.JPG'))->preservingOriginal()->toMediaCollection('feature_photo');
        $categories['tapparfum']->addMedia(database_path('seeders/media/category/5/gift_photo/01KYRBK6R9XS2A8D40HTMD89MM.JPG'))->preservingOriginal()->toMediaCollection('gift_photo');

        // Brands
        $brands = [];
        $brands['josh'] = Brand::create([
            'name' => 'Josh',
            'slug' => 'josh',
            'description' => 'Betaalbare, trendgevoelige tassen en accessoires.',
            'website_url' => null,
            'meta_title' => null,
            'meta_description' => null,
            'is_active' => true,
            'sort_order' => 0,
        ]);
        $brands['qoss'] = Brand::create([
            'name' => 'Qoss',
            'slug' => 'qoss',
            'description' => '<p>Hippe tassen met een vleugje bohemien.</p>',
            'website_url' => null,
            'meta_title' => null,
            'meta_description' => null,
            'is_active' => true,
            'sort_order' => 0,
        ]);
        $brands['micmac-bags'] = Brand::create([
            'name' => 'Micmac Bags',
            'slug' => 'micmac-bags',
            'description' => '<p>Kleurrijke, handgemaakte tassen.</p>',
            'website_url' => null,
            'meta_title' => null,
            'meta_description' => null,
            'is_active' => true,
            'sort_order' => 0,
        ]);
        $brands['micmac-bags']->addMedia(database_path('seeders/media/brand/3/logo/01KY6E817C5SH0YQMQ9J98PEVJ.jpg'))->preservingOriginal()->toMediaCollection('logo');
        $brands['cluse'] = Brand::create([
            'name' => 'Cluse',
            'slug' => 'cluse',
            'description' => 'Minimalistische horloges uit Nederland.',
            'website_url' => null,
            'meta_title' => null,
            'meta_description' => null,
            'is_active' => true,
            'sort_order' => 0,
        ]);
        $brands['oozoo'] = Brand::create([
            'name' => 'Oozoo',
            'slug' => 'oozoo',
            'description' => 'Betaalbare horloges met een uitgesproken statement-look.',
            'website_url' => null,
            'meta_title' => null,
            'meta_description' => null,
            'is_active' => true,
            'sort_order' => 0,
        ]);
        $brands['ixxxi'] = Brand::create([
            'name' => 'ixxxi',
            'slug' => 'ixxxi',
            'description' => 'Modulaire sieraden om zelf mee te combineren.',
            'website_url' => null,
            'meta_title' => null,
            'meta_description' => null,
            'is_active' => true,
            'sort_order' => 0,
        ]);
        $brands['karma'] = Brand::create([
            'name' => 'Karma',
            'slug' => 'karma',
            'description' => 'Sieraden met een verhaal, van natuurlijke materialen.',
            'website_url' => null,
            'meta_title' => null,
            'meta_description' => null,
            'is_active' => true,
            'sort_order' => 0,
        ]);
        $brands['uno-de-50'] = Brand::create([
            'name' => 'Uno de 50',
            'slug' => 'uno-de-50',
            'description' => 'Handgemaakte sieraden uit Spanje, verzilverd.',
            'website_url' => null,
            'meta_title' => null,
            'meta_description' => null,
            'is_active' => true,
            'sort_order' => 0,
        ]);
        $brands['ikki'] = Brand::create([
            'name' => 'Ikki',
            'slug' => 'ikki',
            'description' => 'Kleurrijke, verstelbare sieraden.',
            'website_url' => null,
            'meta_title' => null,
            'meta_description' => null,
            'is_active' => true,
            'sort_order' => 0,
        ]);
        $brands['biba'] = Brand::create([
            'name' => 'Biba',
            'slug' => 'biba',
            'description' => 'Klassieke sieraden met een moderne twist.',
            'website_url' => null,
            'meta_title' => null,
            'meta_description' => null,
            'is_active' => true,
            'sort_order' => 0,
        ]);
        $brands['melano'] = Brand::create([
            'name' => 'Melano',
            'slug' => 'melano',
            'description' => 'Bouw je eigen sieraad met verwisselbare stones.',
            'website_url' => null,
            'meta_title' => null,
            'meta_description' => null,
            'is_active' => true,
            'sort_order' => 0,
        ]);
        $brands['tapparfum'] = Brand::create([
            'name' => 'Tapparfum',
            'slug' => 'tapparfum',
            'description' => '<p></p>',
            'website_url' => null,
            'meta_title' => null,
            'meta_description' => null,
            'is_active' => false,
            'sort_order' => 0,
        ]);
        $brands['charm-london'] = Brand::create([
            'name' => 'Charm London',
            'slug' => 'charm-london',
            'description' => '<p></p>',
            'website_url' => null,
            'meta_title' => null,
            'meta_description' => null,
            'is_active' => false,
            'sort_order' => 0,
        ]);
        $brands['Hide & Stitches'] = Brand::create([
            'name' => 'Hide & Stitches',
            'slug' => 'Hide & Stitches',
            'description' => '<p></p>',
            'website_url' => null,
            'meta_title' => null,
            'meta_description' => null,
            'is_active' => true,
            'sort_order' => 0,
        ]);
        $brands['beagles'] = Brand::create([
            'name' => 'Beagles',
            'slug' => 'beagles',
            'description' => '<p></p>',
            'website_url' => null,
            'meta_title' => null,
            'meta_description' => null,
            'is_active' => true,
            'sort_order' => 0,
        ]);
        $brands['olympic'] = Brand::create([
            'name' => 'Olympic',
            'slug' => 'olympic',
            'description' => '<p></p>',
            'website_url' => null,
            'meta_title' => null,
            'meta_description' => null,
            'is_active' => true,
            'sort_order' => 0,
        ]);
        $brands['zinzi'] = Brand::create([
            'name' => 'Zinzi',
            'slug' => 'zinzi',
            'description' => '<p></p>',
            'website_url' => null,
            'meta_title' => null,
            'meta_description' => null,
            'is_active' => false,
            'sort_order' => 0,
        ]);
        $brands['day-eve'] = Brand::create([
            'name' => 'Day & Eve',
            'slug' => 'day-eve',
            'description' => '<p></p>',
            'website_url' => null,
            'meta_title' => null,
            'meta_description' => null,
            'is_active' => false,
            'sort_order' => 0,
        ]);
        $brands['kalli'] = Brand::create([
            'name' => 'Kalli',
            'slug' => 'kalli',
            'description' => '<p></p>',
            'website_url' => null,
            'meta_title' => null,
            'meta_description' => null,
            'is_active' => false,
            'sort_order' => 0,
        ]);
        $brands['rose-camellia'] = Brand::create([
            'name' => 'Rose & Camellia',
            'slug' => 'rose-camellia',
            'description' => '<p></p>',
            'website_url' => null,
            'meta_title' => null,
            'meta_description' => null,
            'is_active' => true,
            'sort_order' => 0,
        ]);
        $brands['Solid Gold'] = Brand::create([
            'name' => 'Solid Gold',
            'slug' => 'Solid Gold',
            'description' => '<p></p>',
            'website_url' => null,
            'meta_title' => null,
            'meta_description' => null,
            'is_active' => false,
            'sort_order' => 0,
        ]);

        // Stores
        $stores = [];
        $stores['heerhugowaard'] = Store::create([
            'name' => 'Heerhugowaard',
            'slug' => 'heerhugowaard',
            'address_line' => 'Raadhuisplein 8',
            'postal_code' => '1701 EA',
            'city' => 'Heerhugowaard',
            'phone' => '072-5711234',
            'email' => 'heerhugowaard@nice-2-have.nl',
            'shopping_center' => 'Winkelcentrum Centrumwaard',
            'description' => '<p>In winkelcentrum Centrumwaard, met het volledige assortiment onder één dak.</p>',
            'latitude' => '52.6698000',
            'longitude' => '4.8352000',
            'google_maps_url' => null,
            'meta_title' => null,
            'meta_description' => null,
            'is_active' => true,
            'sort_order' => 1,
        ]);
        $stores['heerhugowaard']->addMedia(database_path('seeders/media/store/1/photo/01KYAW1XZ5CJ0NAP1GKEE3PY2F.JPG'))->preservingOriginal()->toMediaCollection('photo');
        $stores['heerhugowaard']->addMedia(database_path('seeders/media/store/1/area_photo/01KYRB1JCT7RMYV53KSV8ZG0GX.JPG'))->preservingOriginal()->toMediaCollection('area_photo');
        $stores['heerhugowaard']->openingHours()->create([
            'day_of_week' => 0,
            'opens_at' => '11:00:00',
            'closes_at' => '17:30:00',
            'is_closed' => false,
        ]);
        $stores['heerhugowaard']->openingHours()->create([
            'day_of_week' => 1,
            'opens_at' => '09:30:00',
            'closes_at' => '17:30:00',
            'is_closed' => false,
        ]);
        $stores['heerhugowaard']->openingHours()->create([
            'day_of_week' => 2,
            'opens_at' => '09:30:00',
            'closes_at' => '17:30:00',
            'is_closed' => false,
        ]);
        $stores['heerhugowaard']->openingHours()->create([
            'day_of_week' => 3,
            'opens_at' => '09:30:00',
            'closes_at' => '17:30:00',
            'is_closed' => false,
        ]);
        $stores['heerhugowaard']->openingHours()->create([
            'day_of_week' => 4,
            'opens_at' => '09:30:00',
            'closes_at' => '18:00:00',
            'is_closed' => false,
        ]);
        $stores['heerhugowaard']->openingHours()->create([
            'day_of_week' => 5,
            'opens_at' => '09:30:00',
            'closes_at' => '17:00:00',
            'is_closed' => false,
        ]);
        $stores['heerhugowaard']->openingHours()->create([
            'day_of_week' => 6,
            'opens_at' => null,
            'closes_at' => null,
            'is_closed' => true,
        ]);
        $stores['castricum'] = Store::create([
            'name' => 'Castricum',
            'slug' => 'castricum',
            'address_line' => 'Geesterduin 50',
            'postal_code' => '1901 JD',
            'city' => 'Castricum',
            'phone' => '0251-651234',
            'email' => 'castricum@nice-2-have.nl',
            'shopping_center' => 'Winkelcentrum Geesterduin',
            'description' => '<p>In winkelcentrum Geesterduin, met een ruim en licht winkelpand.</p>',
            'latitude' => '52.5464000',
            'longitude' => '4.6867000',
            'google_maps_url' => null,
            'meta_title' => null,
            'meta_description' => null,
            'is_active' => true,
            'sort_order' => 2,
        ]);
        $stores['castricum']->addMedia(database_path('seeders/media/store/2/photo/01KYRAYGM7RWJVGKEJAN9KAPFX.JPG'))->preservingOriginal()->toMediaCollection('photo');
        $stores['castricum']->addMedia(database_path('seeders/media/store/2/area_photo/01KYRB2H96388WKN2S6R9N7KP9.JPG'))->preservingOriginal()->toMediaCollection('area_photo');
        $stores['castricum']->openingHours()->create([
            'day_of_week' => 0,
            'opens_at' => '11:00:00',
            'closes_at' => '17:30:00',
            'is_closed' => false,
        ]);
        $stores['castricum']->openingHours()->create([
            'day_of_week' => 1,
            'opens_at' => '09:30:00',
            'closes_at' => '17:30:00',
            'is_closed' => false,
        ]);
        $stores['castricum']->openingHours()->create([
            'day_of_week' => 2,
            'opens_at' => '09:30:00',
            'closes_at' => '17:30:00',
            'is_closed' => false,
        ]);
        $stores['castricum']->openingHours()->create([
            'day_of_week' => 3,
            'opens_at' => '09:30:00',
            'closes_at' => '17:30:00',
            'is_closed' => false,
        ]);
        $stores['castricum']->openingHours()->create([
            'day_of_week' => 4,
            'opens_at' => '09:30:00',
            'closes_at' => '18:00:00',
            'is_closed' => false,
        ]);
        $stores['castricum']->openingHours()->create([
            'day_of_week' => 5,
            'opens_at' => '09:30:00',
            'closes_at' => '17:00:00',
            'is_closed' => false,
        ]);
        $stores['castricum']->openingHours()->create([
            'day_of_week' => 6,
            'opens_at' => null,
            'closes_at' => null,
            'is_closed' => true,
        ]);

        // Products
        $products = [];
        $products['charm-london'] = Product::create([
            'name' => 'Charm London',
            'slug' => 'charm-london',
            'short_description' => null,
            'description' => '<p></p>',
            'price' => null,
            'price_label' => null,
            'is_featured' => false,
            'meta_title' => null,
            'meta_description' => null,
            'is_active' => true,
            'sort_order' => 0,
        ] + ['brand_id' => $brands['charm-london']->id]);
        $products['charm-london']->addMedia(database_path('seeders/media/product/15/gallery/01KYRBW5W0YYSWN08B8021BB8E.JPG'))->preservingOriginal()->toMediaCollection('gallery');
        $products['charm-london']->categories()->attach([$categories['tassen']->id]);
        $products['hide-stitches'] = Product::create([
            'name' => 'Hide & Stitches',
            'slug' => 'hide-stitches',
            'short_description' => null,
            'description' => '<p></p>',
            'price' => null,
            'price_label' => null,
            'is_featured' => false,
            'meta_title' => null,
            'meta_description' => null,
            'is_active' => true,
            'sort_order' => 0,
        ] + ['brand_id' => $brands['Hide & Stitches']->id]);
        $products['hide-stitches']->addMedia(database_path('seeders/media/product/16/gallery/01KYRC65VMR5H9VJ1YQB51DZTG.JPG'))->preservingOriginal()->toMediaCollection('gallery');
        $products['hide-stitches']->categories()->attach([$categories['tassen']->id]);
        $products['beagles'] = Product::create([
            'name' => 'Beagles',
            'slug' => 'beagles',
            'short_description' => null,
            'description' => '<p></p>',
            'price' => null,
            'price_label' => null,
            'is_featured' => false,
            'meta_title' => null,
            'meta_description' => null,
            'is_active' => true,
            'sort_order' => 0,
        ] + ['brand_id' => $brands['beagles']->id]);
        $products['beagles']->addMedia(database_path('seeders/media/product/17/gallery/01KYRDAGJDC2KM2SZD979VRDJ5.webp'))->preservingOriginal()->toMediaCollection('gallery');
        $products['beagles']->categories()->attach([$categories['tassen']->id]);
        $products['cluse'] = Product::create([
            'name' => 'Cluse',
            'slug' => 'cluse',
            'short_description' => null,
            'description' => '<p></p>',
            'price' => null,
            'price_label' => null,
            'is_featured' => false,
            'meta_title' => null,
            'meta_description' => null,
            'is_active' => true,
            'sort_order' => 0,
        ] + ['brand_id' => $brands['cluse']->id]);
        $products['cluse']->addMedia(database_path('seeders/media/product/18/gallery/01KYRCKK1Z6VV1B74C2CWQ1M5K.JPG'))->preservingOriginal()->toMediaCollection('gallery');
        $products['cluse']->categories()->attach([$categories['horloges']->id]);
        $products['oozoo'] = Product::create([
            'name' => 'Oozoo',
            'slug' => 'oozoo',
            'short_description' => null,
            'description' => '<p></p>',
            'price' => null,
            'price_label' => null,
            'is_featured' => false,
            'meta_title' => null,
            'meta_description' => null,
            'is_active' => true,
            'sort_order' => 0,
        ] + ['brand_id' => $brands['oozoo']->id]);
        $products['oozoo']->addMedia(database_path('seeders/media/product/19/gallery/01KYRCNK9YV06ZPYR6EWE5M8AK.JPG'))->preservingOriginal()->toMediaCollection('gallery');
        $products['oozoo']->categories()->attach([$categories['horloges']->id]);
        $products['Olympic'] = Product::create([
            'name' => 'Olympic',
            'slug' => 'Olympic',
            'short_description' => null,
            'description' => '<p></p>',
            'price' => null,
            'price_label' => null,
            'is_featured' => false,
            'meta_title' => null,
            'meta_description' => null,
            'is_active' => true,
            'sort_order' => 0,
        ] + ['brand_id' => $brands['olympic']->id]);
        $products['Olympic']->addMedia(database_path('seeders/media/product/20/gallery/01KYRD3WA1Y0J6AXWV3EMWEDM0.webp'))->preservingOriginal()->toMediaCollection('gallery');
        $products['Olympic']->categories()->attach([$categories['horloges']->id]);
        $products['zinzi'] = Product::create([
            'name' => 'Zinzi',
            'slug' => 'zinzi',
            'short_description' => null,
            'description' => '<p></p>',
            'price' => null,
            'price_label' => null,
            'is_featured' => false,
            'meta_title' => null,
            'meta_description' => null,
            'is_active' => true,
            'sort_order' => 0,
        ] + ['brand_id' => $brands['zinzi']->id]);
        $products['zinzi']->addMedia(database_path('seeders/media/product/21/gallery/01KYRD68Q4T7BANNNBFF4WSB4Y.JPG'))->preservingOriginal()->toMediaCollection('gallery');
        $products['zinzi']->categories()->attach([$categories['horloges']->id]);
        $products['melano'] = Product::create([
            'name' => 'Melano',
            'slug' => 'melano',
            'short_description' => null,
            'description' => '<p></p>',
            'price' => null,
            'price_label' => null,
            'is_featured' => false,
            'meta_title' => null,
            'meta_description' => null,
            'is_active' => true,
            'sort_order' => 0,
        ] + ['brand_id' => $brands['melano']->id]);
        $products['melano']->addMedia(database_path('seeders/media/product/22/gallery/01KYS2NKACCNPH13XYJJXTDA8C.jpg'))->preservingOriginal()->toMediaCollection('gallery');
        $products['melano']->categories()->attach([$categories['sieraden']->id]);
        $products['karma'] = Product::create([
            'name' => 'Karma',
            'slug' => 'karma',
            'short_description' => null,
            'description' => '<p></p>',
            'price' => null,
            'price_label' => null,
            'is_featured' => false,
            'meta_title' => null,
            'meta_description' => null,
            'is_active' => true,
            'sort_order' => 0,
        ] + ['brand_id' => $brands['karma']->id]);
        $products['karma']->addMedia(database_path('seeders/media/product/23/gallery/01KYS2SRRY9VZ730EMY49AWAJJ.JPG'))->preservingOriginal()->toMediaCollection('gallery');
        $products['karma']->categories()->attach([$categories['sieraden']->id]);
        $products['zinzi-1'] = Product::create([
            'name' => 'Zinzi',
            'slug' => 'zinzi-1',
            'short_description' => null,
            'description' => '<p></p>',
            'price' => null,
            'price_label' => null,
            'is_featured' => false,
            'meta_title' => null,
            'meta_description' => null,
            'is_active' => true,
            'sort_order' => 0,
        ] + ['brand_id' => $brands['zinzi']->id]);
        $products['zinzi-1']->addMedia(database_path('seeders/media/product/24/gallery/01KYS49YM6A8T8SSC949NA10F4.jpg'))->preservingOriginal()->toMediaCollection('gallery');
        $products['zinzi-1']->categories()->attach([$categories['sieraden']->id]);
        $products['ixxxi'] = Product::create([
            'name' => 'Ixxxi',
            'slug' => 'ixxxi',
            'short_description' => null,
            'description' => '<p></p>',
            'price' => null,
            'price_label' => null,
            'is_featured' => false,
            'meta_title' => null,
            'meta_description' => null,
            'is_active' => true,
            'sort_order' => 0,
        ] + ['brand_id' => $brands['ixxxi']->id]);
        $products['ixxxi']->addMedia(database_path('seeders/media/product/25/gallery/01KYS2XVK540K8GBCX6P6JK4A9.JPG'))->preservingOriginal()->toMediaCollection('gallery');
        $products['ixxxi']->categories()->attach([$categories['sieraden']->id]);
        $products['qoss'] = Product::create([
            'name' => 'Qoss',
            'slug' => 'qoss',
            'short_description' => null,
            'description' => '<p></p>',
            'price' => null,
            'price_label' => null,
            'is_featured' => false,
            'meta_title' => null,
            'meta_description' => null,
            'is_active' => true,
            'sort_order' => 0,
        ] + ['brand_id' => $brands['qoss']->id]);
        $products['qoss']->addMedia(database_path('seeders/media/product/26/gallery/01KYS3HVF915W25E0MMRZTWABK.JPG'))->preservingOriginal()->toMediaCollection('gallery');
        $products['qoss']->categories()->attach([$categories['sieraden']->id]);
        $products['day-eve'] = Product::create([
            'name' => 'Day & Eve',
            'slug' => 'day-eve',
            'short_description' => null,
            'description' => '<p></p>',
            'price' => null,
            'price_label' => null,
            'is_featured' => false,
            'meta_title' => null,
            'meta_description' => null,
            'is_active' => true,
            'sort_order' => 0,
        ] + ['brand_id' => $brands['day-eve']->id]);
        $products['day-eve']->addMedia(database_path('seeders/media/product/27/gallery/01KYS32ZDKHVZTWGSXH5JQ6G24.JPG'))->preservingOriginal()->toMediaCollection('gallery');
        $products['day-eve']->categories()->attach([$categories['sieraden']->id]);
        $products['biba'] = Product::create([
            'name' => 'Biba',
            'slug' => 'biba',
            'short_description' => null,
            'description' => '<p></p>',
            'price' => null,
            'price_label' => null,
            'is_featured' => false,
            'meta_title' => null,
            'meta_description' => null,
            'is_active' => true,
            'sort_order' => 0,
        ] + ['brand_id' => $brands['biba']->id]);
        $products['biba']->addMedia(database_path('seeders/media/product/28/gallery/01KYS38E1TS10GNSJWCVSZHBAR.JPG'))->preservingOriginal()->toMediaCollection('gallery');
        $products['biba']->categories()->attach([$categories['sieraden']->id]);
        $products['josh'] = Product::create([
            'name' => 'Josh',
            'slug' => 'josh',
            'short_description' => null,
            'description' => '<p></p>',
            'price' => null,
            'price_label' => null,
            'is_featured' => false,
            'meta_title' => null,
            'meta_description' => null,
            'is_active' => true,
            'sort_order' => 0,
        ] + ['brand_id' => $brands['josh']->id]);
        $products['josh']->addMedia(database_path('seeders/media/product/29/gallery/01KYS417Q6S0CAZH7MVJYNYG3Y.webp'))->preservingOriginal()->toMediaCollection('gallery');
        $products['josh']->categories()->attach([$categories['sieraden']->id]);
        $products['rose-camellia'] = Product::create([
            'name' => 'Rose & Camellia',
            'slug' => 'rose-camellia',
            'short_description' => null,
            'description' => '<p></p>',
            'price' => null,
            'price_label' => null,
            'is_featured' => false,
            'meta_title' => null,
            'meta_description' => null,
            'is_active' => true,
            'sort_order' => 0,
        ] + ['brand_id' => $brands['rose-camellia']->id]);
        $products['rose-camellia']->addMedia(database_path('seeders/media/product/30/gallery/01KYS3WGQJN8MRFHX4BRRKN4AB.jpg'))->preservingOriginal()->toMediaCollection('gallery');
        $products['rose-camellia']->categories()->attach([$categories['sieraden']->id]);
        $products['solid-gold'] = Product::create([
            'name' => 'Solid Gold',
            'slug' => 'solid-gold',
            'short_description' => null,
            'description' => '<p></p>',
            'price' => null,
            'price_label' => null,
            'is_featured' => false,
            'meta_title' => null,
            'meta_description' => null,
            'is_active' => true,
            'sort_order' => 0,
        ] + ['brand_id' => $brands['Solid Gold']->id]);
        $products['solid-gold']->addMedia(database_path('seeders/media/product/31/gallery/01KYS47SE032BMV3TS1YWY505J.png'))->preservingOriginal()->toMediaCollection('gallery');
        $products['solid-gold']->categories()->attach([$categories['sieraden']->id]);

        // Hero slides
        $slide1 = HeroSlide::create([
            'kicker' => 'Nieuwe collectie',
            'title' => 'Trendy tassen voor elk moment',
            'subtitle' => 'Van ruime shoppers tot elegante crossbody\'s. Ontdek de nieuwste tassen van Josh, Qoss en Micmac Bags.',
            'button_label' => 'Bekijk tassen',
            'button_url' => '/categorie/tassen',
            'sort_order' => 1,
            'is_active' => true,
        ]);
        $slide1->addMedia(database_path('seeders/media/hero_slide/1/image/01KYAVPAZ8ZGEERG1FEPJP1C1Y.JPG'))->preservingOriginal()->toMediaCollection('image');
        $slide2 = HeroSlide::create([
            'kicker' => 'Toonaangevende merken',
            'title' => 'Hip & betaalbaar, elke week anders',
            'subtitle' => 'Cluse, Oozoo, ixxxi en nog veel meer. Ons assortiment wisselt continu.',
            'button_label' => 'Bekijk merken',
            'button_url' => '/merken',
            'sort_order' => 2,
            'is_active' => true,
        ]);
        $slide2->addMedia(database_path('seeders/media/hero_slide/2/image/01KYAVPY7TZ92R6Q5KA6RYXBRG.JPG'))->preservingOriginal()->toMediaCollection('image');
        $slide3 = HeroSlide::create([
            'kicker' => 'Twee winkels, één stijl',
            'title' => 'Altijd een Nice2Have in de buurt',
            'subtitle' => 'Winkelcentrum Centrumwaard in Heerhugowaard en winkelcentrum Geesterduin in Castricum.',
            'button_label' => 'Bekijk onze winkels',
            'button_url' => '/#winkels',
            'sort_order' => 3,
            'is_active' => true,
        ]);
        $slide3->addMedia(database_path('seeders/media/hero_slide/3/image/01KYAVR0RMQPK2T69P95PJYSXX.JPG'))->preservingOriginal()->toMediaCollection('image');

        // USP blocks
        UspBlock::create([
            'icon' => 'fas fa-store',
            'title' => 'Twee winkels',
            'text' => 'Heerhugowaard en Castricum, allebei met een eigen sfeer en assortiment.',
            'sort_order' => 1,
            'is_active' => true,
        ]);
        UspBlock::create([
            'icon' => 'fas fa-gem',
            'title' => 'Toonaangevende merken',
            'text' => 'Een zorgvuldig samengestelde selectie van merken die je overal ziet terugkomen.',
            'sort_order' => 2,
            'is_active' => true,
        ]);
        UspBlock::create([
            'icon' => 'fas fa-heart',
            'title' => 'Hip & betaalbaar',
            'text' => 'Trendgevoelige items zonder dat het je een fortuin kost.',
            'sort_order' => 3,
            'is_active' => true,
        ]);

        // Pages
        $pages = [];
        $pages['over-ons'] = Page::create([
            'title' => 'Over ons',
            'slug' => 'over-ons',
            'body' => '<p>Nice2Have is een trendjuwelier en conceptstore met twee winkels: Heerhugowaard en Castricum. Ons assortiment wisselt continu, dus kom vooral eens langs.</p>',
            'template' => null,
            'meta_title' => null,
            'meta_description' => null,
            'is_published' => true,
            'published_at' => '2026-07-22 14:19:08',
        ]);

        // Menu items
        MenuItem::create([
            'location' => 'top',
            'label' => 'Home',
            'url' => '/',
            'target' => '_self',
            'sort_order' => 1,
            'is_active' => true,
        ]);
        MenuItem::create([
            'location' => 'top',
            'label' => 'Tassen',
            'url' => null,
            'target' => '_self',
            'sort_order' => 2,
            'is_active' => true,
        ] + [
            'linkable_type' => Category::class,
            'linkable_id' => $categories['tassen']->id,
        ]);
        MenuItem::create([
            'location' => 'top',
            'label' => 'Sieraden',
            'url' => null,
            'target' => '_self',
            'sort_order' => 3,
            'is_active' => true,
        ] + [
            'linkable_type' => Category::class,
            'linkable_id' => $categories['sieraden']->id,
        ]);
        MenuItem::create([
            'location' => 'top',
            'label' => 'Horloges',
            'url' => null,
            'target' => '_self',
            'sort_order' => 4,
            'is_active' => true,
        ] + [
            'linkable_type' => Category::class,
            'linkable_id' => $categories['horloges']->id,
        ]);
        MenuItem::create([
            'location' => 'top',
            'label' => 'Riemen & Sjaals',
            'url' => null,
            'target' => '_self',
            'sort_order' => 5,
            'is_active' => true,
        ] + [
            'linkable_type' => Category::class,
            'linkable_id' => $categories['riemen-sjaals']->id,
        ]);
        MenuItem::create([
            'location' => 'top',
            'label' => 'Tapparfum',
            'url' => null,
            'target' => '_self',
            'sort_order' => 6,
            'is_active' => true,
        ] + [
            'linkable_type' => Category::class,
            'linkable_id' => $categories['tapparfum']->id,
        ]);
        MenuItem::create([
            'location' => 'top',
            'label' => 'Contact',
            'url' => '/contact',
            'target' => '_self',
            'sort_order' => 7,
            'is_active' => true,
        ]);
        MenuItem::create([
            'location' => 'footer',
            'label' => 'Winkel Heerhugowaard',
            'url' => null,
            'target' => '_self',
            'sort_order' => 1,
            'is_active' => true,
        ] + [
            'linkable_type' => Store::class,
            'linkable_id' => $stores['heerhugowaard']->id,
        ]);
        MenuItem::create([
            'location' => 'footer',
            'label' => 'Winkel Castricum',
            'url' => null,
            'target' => '_self',
            'sort_order' => 2,
            'is_active' => true,
        ] + [
            'linkable_type' => Store::class,
            'linkable_id' => $stores['castricum']->id,
        ]);
        MenuItem::create([
            'location' => 'footer',
            'label' => 'Over ons',
            'url' => null,
            'target' => '_self',
            'sort_order' => 3,
            'is_active' => true,
        ] + [
            'linkable_type' => Page::class,
            'linkable_id' => $pages['over-ons']->id,
        ]);
        MenuItem::create([
            'location' => 'footer',
            'label' => 'Contact',
            'url' => '/contact',
            'target' => '_self',
            'sort_order' => 4,
            'is_active' => true,
        ]);

        // Schema / site settings
        SchemaSetting::set('contact_page', [
                'image' => 'contact-page/01KYSKDNNWVDTDR7PVVA8B49YK.JPG',
                'kicker' => null,
                'title' => null,
                'subtitle' => null,
            ]);
        SchemaSetting::set('organization', [
                'name' => 'Nice2Have',
                'email' => 'info@nice-2-have.nl',
                'instagram_url' => 'https://www.instagram.com/nice2have',
                'facebook_url' => 'https://www.facebook.com/nice2have',
            ]);

    }
}
